### PR TITLE
Changin steps to run application @ readme

### PR DESCRIPTION
**Pull request by lfreneda**
Hello there, in order to run the samples I've followed these steps that I updated @ readme file 
:yum:

### CODE REVIEW

**Comment by lfreneda** [comment]
@akoeplinger hello?! :fearful:

**Comment by akoeplinger** [comment]
I'm terribly sorry, I completely missed this PR :cry: 

From looking at your changes this seems to make it so that you'd need to clone the repo to run the instructions, correct? I explicitly wanted to avoid that when I created the repo. The goal was to get people up and running with an ASP.NET vNext environment as fast as possible.

That said, due to the rapid development and changes of vNext to DNX/DNVM etc. I don't think I'll get to updating this repo until the new system stabilizes a bit more (possibly with the beta5 release).

**Comment by lfreneda** [comment]
makes sense!

I'm closing this PR.

Thank you :dancers:

**Comment by akoeplinger** [comment]
Thank you for taking the time to contribute and sorry again for me not being responsive!

**Pull request closed without merging**
